-- ============================================================
-- Call Center CRM — Full Database Schema
-- Run in phpMyAdmin or: mysql -u root crm_db < database.sql
-- ============================================================

-- Create and select the database
CREATE DATABASE IF NOT EXISTS crm_db
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE crm_db;

-- -------------------------------------------------------
-- Drop tables in FK-safe order before recreating
-- -------------------------------------------------------
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS calls;
DROP TABLE IF EXISTS clients;
DROP TABLE IF EXISTS agents;
SET FOREIGN_KEY_CHECKS = 1;

-- -------------------------------------------------------
-- Table: agents
-- Stores login credentials for call center agents.
-- Passwords are stored as bcrypt hashes (password_hash).
-- -------------------------------------------------------
CREATE TABLE agents (
    id         INT UNSIGNED    AUTO_INCREMENT PRIMARY KEY,
    name       VARCHAR(100)    NOT NULL,
    email      VARCHAR(150)    NOT NULL UNIQUE,
    password   VARCHAR(255)    NOT NULL,        -- bcrypt hash
    role       ENUM('agent','admin') NOT NULL DEFAULT 'agent',
    is_active  TINYINT(1)      NOT NULL DEFAULT 1,
    created_at DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -------------------------------------------------------
-- Table: clients
-- Stores customer/client records.
-- -------------------------------------------------------
CREATE TABLE clients (
    id         INT UNSIGNED    AUTO_INCREMENT PRIMARY KEY,
    name       VARCHAR(100)    NOT NULL,
    phone      VARCHAR(30)     NOT NULL,
    email      VARCHAR(150)    DEFAULT NULL,
    notes      TEXT            DEFAULT NULL,
    created_at DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -------------------------------------------------------
-- Table: calls
-- Stores every call/ticket associated with a client.
-- FK: calls.client_id → clients.id (CASCADE delete)
-- -------------------------------------------------------
CREATE TABLE calls (
    id          INT UNSIGNED    AUTO_INCREMENT PRIMARY KEY,
    client_id   INT UNSIGNED    NOT NULL,
    problem     TEXT            NOT NULL,
    call_date   DATE            NOT NULL,
    status      ENUM('Traité','En attente','À rappeler') NOT NULL DEFAULT 'En attente',
    created_at  DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_calls_client
        FOREIGN KEY (client_id) REFERENCES clients(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -------------------------------------------------------
-- Indexes for performance
-- -------------------------------------------------------
CREATE INDEX idx_calls_client_id  ON calls(client_id);
CREATE INDEX idx_calls_status     ON calls(status);
CREATE INDEX idx_calls_call_date  ON calls(call_date);
CREATE INDEX idx_clients_name     ON clients(name);

-- -------------------------------------------------------
-- Seed data — Demo agents
-- IMPORTANT: These hashes correspond to the plain-text password: "password"
-- Generated with: password_hash('password', PASSWORD_BCRYPT)
-- Run seed.php instead if you want fresh hashes generated by your PHP version.
-- -------------------------------------------------------
INSERT INTO agents (name, email, password, role) VALUES
(
    'Sophie Martin',
    'sophie@callcenter.com',
    '$2y$12$8HwqaNGHfCGaXYF7xBOkb.3skxCJ7J3T5oGv9fGVS3jcfXpX39k0K',
    'admin'
),
(
    'Lucas Bernard',
    'lucas@callcenter.com',
    '$2y$12$8HwqaNGHfCGaXYF7xBOkb.3skxCJ7J3T5oGv9fGVS3jcfXpX39k0K',
    'agent'
);

-- NOTE: The hash above may not match your PHP environment.
-- Run http://localhost/call%20center%20agent/seed.php to regenerate correct hashes.

-- -------------------------------------------------------
-- Seed data — Sample clients
-- -------------------------------------------------------
INSERT INTO clients (name, phone, email) VALUES
('Jean Dupont',     '0601234567', 'jean.dupont@email.com'),
('Marie Leclerc',   '0698765432', 'marie.leclerc@email.com'),
('Pierre Lambert',  '0712345678', 'pierre.lambert@email.com'),
('Claire Fontaine', '0623456789', 'claire.fontaine@email.com'),
('Antoine Morin',   '0745678901', 'antoine.morin@email.com');

-- -------------------------------------------------------
-- Seed data — Sample calls
-- -------------------------------------------------------
INSERT INTO calls (client_id, problem, call_date, status) VALUES
(1, 'Problème de facturation — double prélèvement détecté.',        '2026-04-20', 'Traité'),
(1, 'Demande de modification du forfait abonnement.',               '2026-04-22', 'En attente'),
(2, 'Panne de connexion internet depuis 3 jours.',                  '2026-04-21', 'À rappeler'),
(3, 'Réclamation sur la qualité du service client.',                '2026-04-19', 'Traité'),
(4, 'Demande d\'informations sur les nouveaux tarifs.',             '2026-04-23', 'En attente'),
(5, 'Résiliation du contrat souhaitée pour fin de mois.',           '2026-04-18', 'À rappeler'),
(2, 'Mise à jour des coordonnées bancaires.',                       '2026-04-22', 'Traité'),
(3, 'Demande de remboursement suite à une erreur de facturation.', '2026-04-23', 'En attente');
